services:
  selenoid:
    image: aerokube/selenoid:latest-release
    ports:
      - "4444:4444"
    volumes:
      - "./config:/etc/selenoid/"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./video:/opt/selenoid/video"
      - "./logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=./video
      - SELENOID_DISABLE_DOCKER_CLIENT_VERSION_CHECK=true
    command: [
      "-conf", "/etc/selenoid/browsers.json",
      "-video-output-dir", "/opt/selenoid/video",
      "-capture-driver-logs",
      "-limit", "5",
      "-disable-docker", "false"
    ]
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:4444/status", "-q", "-T", "10"]
      interval: 10s
      timeout: 5s
      retries: 5

  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    ports:
      - "8989:8080"
    depends_on:
      selenoid:
        condition: service_healthy
    command: ["--selenoid-uri", "http://selenoid:4444"]
